//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFGesAgro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cidade
    {
        public Cidade()
        {
            this.Fazenda = new HashSet<Fazenda>();
            this.Pessoa = new HashSet<Pessoa>();
        }
    
        public int CidCod { get; set; }
        public string CidNom { get; set; }
        public int EstCod { get; set; }
    
        public virtual Estado Estado { get; set; }
        public virtual ICollection<Fazenda> Fazenda { get; set; }
        public virtual ICollection<Pessoa> Pessoa { get; set; }
    }
}
