//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFGesAgro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cultura
    {
        public Cultura()
        {
            this.Variedade = new HashSet<Variedade>();
            this.Talhao = new HashSet<Talhao>();
        }
    
        public int CulCod { get; set; }
        public string CulNom { get; set; }
        public string CulSta { get; set; }
    
        public virtual ICollection<Variedade> Variedade { get; set; }
        public virtual ICollection<Talhao> Talhao { get; set; }
    }
}
