//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFGesAgro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustoEstimado
    {
        public int CusEstCod { get; set; }
        public int CusEstTlhCod { get; set; }
        public decimal CusEstVlr { get; set; }
        public string CusEstObs { get; set; }
        public int CusEstItm { get; set; }
    
        public virtual CustoItens CustoItens { get; set; }
        public virtual Talhao Talhao { get; set; }
    }
}
