//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFGesAgro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustoPrevisto
    {
        public int CusPrevCod { get; set; }
        public int CusPrevTlhCod { get; set; }
        public int CusPrevItm { get; set; }
        public string CusPrevObs { get; set; }
        public decimal CusPrevVlr { get; set; }
    
        public virtual CustoItens CustoItens { get; set; }
        public virtual Talhao Talhao { get; set; }
    }
}
