//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFGesAgro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estado
    {
        public Estado()
        {
            this.Cidade = new HashSet<Cidade>();
            this.Fazenda = new HashSet<Fazenda>();
            this.Pessoa = new HashSet<Pessoa>();
        }
    
        public int EstCod { get; set; }
        public string EstNom { get; set; }
        public string EstSig { get; set; }
    
        public virtual ICollection<Cidade> Cidade { get; set; }
        public virtual ICollection<Fazenda> Fazenda { get; set; }
        public virtual ICollection<Pessoa> Pessoa { get; set; }
    }
}
