//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFGesAgro.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Fazenda
    {
        public Fazenda()
        {
            this.Talhao = new HashSet<Talhao>();
        }
    
        public int FazCod { get; set; }
        public string FazNom { get; set; }
        public string FazDoc { get; set; }
        public string FazIns { get; set; }
        public string FazCom { get; set; }
        public string FazNIRF { get; set; }
        public Nullable<decimal> FazAre { get; set; }
        public Nullable<decimal> FazLat { get; set; }
        public Nullable<decimal> FazLon { get; set; }
        [DataType(DataType.Date), DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> FazDat { get; set; }
        public string FazEnd { get; set; }
        public string FazBai { get; set; }
        public string FazNro { get; set; }
        public int FazCid { get; set; }
        public int FazEst { get; set; }
        public string FazCep { get; set; }
        public string FazEmail { get; set; }
        public string FazFone1 { get; set; }
        public string FazCel { get; set; }
        public string FazFax { get; set; }
        public int FazPes { get; set; }
    
        public virtual Cidade Cidade { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual Pessoa Pessoa { get; set; }
        public virtual ICollection<Talhao> Talhao { get; set; }
    }
}
