//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFGesAgro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pessoa
    {
        public Pessoa()
        {
            this.Fazenda = new HashSet<Fazenda>();
        }
    
        public int PesCod { get; set; }
        public string PesNom { get; set; }
        public string PesEnd { get; set; }
        public string PesBai { get; set; }
        public string PesNro { get; set; }
        public string PesCom { get; set; }
        public string PesCep { get; set; }
        public string PesCpf { get; set; }
        public string PesRg { get; set; }
        public string PesIns { get; set; }
        public string PesTip { get; set; }
        public string PesEmail { get; set; }
        public int EstCod { get; set; }
        public int CidCod { get; set; }
        public string PesSta { get; set; }
        public string PesFon { get; set; }
        public string PesCel { get; set; }
        public string PesUsr { get; set; }
    
        public virtual Cidade Cidade { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual ICollection<Fazenda> Fazenda { get; set; }
    }
}
