//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFGesAgro.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Talhao
    {
        public Talhao()
        {
            this.CustoEstimado = new HashSet<CustoEstimado>();
            this.CustoPrevisto = new HashSet<CustoPrevisto>();
        }
    
        public int TlhCod { get; set; }
        public string TlhDes { get; set; }
        public decimal TlhQtd { get; set; }
        public string TlhSisCul { get; set; }
        public decimal TlhAre { get; set; }
        public decimal TlhAreApp { get; set; }
        public string TlhSit { get; set; }
        [DataType(DataType.Date), DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime TlhDat { get; set; }
        public int VdeCod { get; set; }
        public int CulCod { get; set; }
        public Nullable<int> TlhFazCod { get; set; }
        public Nullable<int> TlhSfrCod { get; set; }
    
        public virtual Cultura Cultura { get; set; }
        public virtual ICollection<CustoEstimado> CustoEstimado { get; set; }
        public virtual ICollection<CustoPrevisto> CustoPrevisto { get; set; }
        public virtual Fazenda Fazenda { get; set; }
        public virtual Safra Safra { get; set; }
        public virtual Variedade Variedade { get; set; }
    }
}
