//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFGesAgro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Variedade
    {
        public Variedade()
        {
            this.Talhao = new HashSet<Talhao>();
        }
    
        public int VdeCod { get; set; }
        public string VdeNom { get; set; }
        public string VdeSta { get; set; }
        public int CulCod { get; set; }
    
        public virtual Cultura Cultura { get; set; }
        public virtual ICollection<Talhao> Talhao { get; set; }
    }
}
